### ISSUE TITLE
Reference Velocity

### ISSUE THREAD

**Issue by amdshameer** [jmichalczyk/motion-planning-walking#1]
Hi @jmichalczyk 
I was able to generate trajectories for feet and CoM. Is it possible to get the velocities too?
And the code was well documented.

**Comment by janmichl** [comment]
Hi @amdshameer 
No, there is no call to obtain velocities. I used accelerations for the whole-body control. 
What you can do is change the expressions for polynomials to obtain velocities in lines 92-101 in the file `plotting.py`.
